### PR TITLE
update pkg url. The old download no longer exists

### PR DESCRIPTION
**Pull request by relvao**

### CODE REVIEW

**Comment by steve450** [comment]
Thanks for the PR. One of our users had just run into a problem with this module yesterday, but we hadn't had time to look into it. I'm guessing this was it. Thanks again.

**Comment by relvao** [comment]
@steve450 You're welcome. Can you please add a tag, so I can update our boxen config to use your repo?

**Comment by steve450** [comment]
@relvao all set. Released a new version - 1.0.1

**Comment by relvao** [comment]
Thanks.

**Pull request merged**
